<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\ComputeMultiplicityCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/ComputeMultiplicityCommand.php';
include_once $this->targetDirs[3].'/src/Service/CombineService.php';
include_once $this->targetDirs[3].'/src/Service/SubsetProblemSolver.php';
include_once $this->targetDirs[3].'/src/Service/SplitStringService.php';

$this->privates['App\Command\ComputeMultiplicityCommand'] = $instance = new \App\Command\ComputeMultiplicityCommand(($this->privates['App\Service\CombineService'] ?? ($this->privates['App\Service\CombineService'] = new \App\Service\CombineService())), ($this->privates['App\Service\SubsetProblemSolver'] ?? ($this->privates['App\Service\SubsetProblemSolver'] = new \App\Service\SubsetProblemSolver())), ($this->privates['App\Service\SplitStringService'] ?? ($this->privates['App\Service\SplitStringService'] = new \App\Service\SplitStringService())));

$instance->setName('app:compute-multiplicity');

return $instance;
