<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\CombineService' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/CombineService.php';

return $this->privates['App\Service\CombineService'] = new \App\Service\CombineService();
