<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRzBkvV1\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRzBkvV1/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerRzBkvV1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerRzBkvV1\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerRzBkvV1\srcApp_KernelTestDebugContainer(array(
    'container.build_hash' => 'RzBkvV1',
    'container.build_id' => '296f2d5b',
    'container.build_time' => 1548525779,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRzBkvV1');
