<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXSaqFpR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXSaqFpR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXSaqFpR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXSaqFpR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXSaqFpR\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'XSaqFpR',
    'container.build_id' => '15f806e3',
    'container.build_time' => 1548532293,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXSaqFpR');
